config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users
  
  root to: "homes#top"
  get "home/about"=>"homes#about"
  get "search" => "searches#search"
  
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only:[:create, :destroy]
    resources :book_comments, only:[:create, :destroy]
  end
  
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only:[:create, :destroy]
    
    get "follows" => "relationships#follows", as: "follows"
    get "followers" => "relationships#followers", as: "followers"
    
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  validates :title, presence: true
  validates :body, presence: true, length: {maximum:200}
  
  # likes method
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
  
  # search methods
  def self.looks(searchword, search)
    
    if search == "perfect"
      Book.where("title LIKE?", searchword)
      
    elsif search == "forward"
      Book.where("title LIKE?", searchword + "%")
      
    elsif search == "backward"
      Book.where("title LIKE?", "%" + searchword)
      
    else
      Book.where("title LIKE?", "%" + searchword + "%")
      
    end
    
  end
  
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  
  belongs_to :follow, class_name: "User"
  belongs_to :follower, class_name: "User"
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  # follow/follower model associations via foreign keys
  has_many :follows, class_name: "Relationship", foreign_key: "follow_id", dependent: :destroy
  has_many :followers, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  
  has_many :following_users, through: :follows, source: :follower
  has_many :follower_users, through: :followers, source: :follow
  
  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

# user's profile_image
  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end
  
  # follow/follower methods
  def follow(user_id)
    follows.create(follower_id: user_id)
  end
  
  def unfollow(user_id)
    follows.find_by(follower_id: user_id).destroy
  end
  
  def following?(user)
    following_users.include?(user)
  end
  
  # search methods
  def self.looks(searchword, search)
    
    if search == "perfect"
      User.where("name LIKE?", searchword)
      
    elsif search == "forward"
      User.where("name LIKE?", searchword + "%")
      
    elsif search == "backward"
      User.where("name LIKE?", "%" + searchword)
      
    else
      User.where("name LIKE?", "%" + searchword + "%")
      
    end
    
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
    root_path
  end
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  
  def create
    @book = Book.find(params[:book_id])
    @comment = current_user.book_comments.new(book_comment_params)
    @comment.book_id = @book.id
    @comment.save
  end
  
  def destroy
    @book = Book.find(params[:book_id])
    @book_comment = BookComment.find(params[:id])
    @book_comment.destroy
  end
  
  private
  
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update]

  def show
    @book = Book.find(params[:id])
    @new_book = Book.new
    @book_comment = BookComment.new
    @user = @book.user
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end
  
  def ensure_correct_user
    book = Book.find(params[:id])
    unless book.user_id == current_user.id
      redirect_to books_path
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    @user = User.find(params[:user_id])
    current_user.follow(params[:user_id])
    @users = User.all
    # redirect_to request.referer
  end

  def destroy
    @user = User.find(params[:user_id])
    current_user.unfollow(params[:user_id])
    @users = User.all
    # redirect_to request.referer
  end

  def follows
    @user = User.find(params[:user_id])
    @users = @user.following_users
  end

  def followers
    @user = User.find(params[:user_id])
    @users = @user.follower_users
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  
  def search
    @searchword = params[:searchword]
    @range = params[:range]
    @search = params[:search]
    
    if @range == "User"
      @users = User.looks(@searchword, @search)
      
    else
      @books = Book.looks(@searchword, @search)
      
    end
    
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
    
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_comments.html.erb
<% book.book_comments.each do |book_comment| %>
  <%= link_to user_path(book_comment.user_id), class: "text-decoration-none" do %>
    <%= image_tag book_comment.user.get_profile_image, size:"50x50" %>
  <% end %>
  
  <%= book_comment.comment %>
  
  <% if book_comment.user_id == current_user.id %>
    <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, remote: true, class: "btn btn-danger btn-sm" %>
  <% end %>
  <p>
    <%= link_to book_comment.user.name, user_path(book_comment.user_id) %>
  </p>
  
<% end %>

app/views/book_comments/_form.html.erb
<%= form_with model: [book, book_comment], local: false do |f| %>
  <div class="form-group">
    <%= f.text_area :comment, rows: "5" , class: "form-control book_book_comment" %>
  </div>
  <div class="form-group">
    <%= f.submit "送信" %>
  </div>
<% end %>

app/views/book_comments/create.js.erb
$("#book_comments").html("<%= j(render "book_comments/comments", book: @book) %>");
$("#comment_count").html("<%= @book.book_comments.count %>")
$("textarea").val('');

app/views/book_comments/destroy.js.erb
$('#book_comments').html("<%= j(render "book_comments/comments", book: @book) %>");
$("#comment_count").html("<%= @book.book_comments.count %>")

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to(book.user) do %>
          <%= image_tag book.user.get_profile_image, size:'50x50' %>
          <% end %>
        </td>
        <td><%= link_to book.title,book %></td>
        <td><%= book.body %></td>
        <td id="favorite_btn_<%= book.id %>">
          <%= render "favorites/favorite-btn", book: book %>
        </td>
        <td>コメント数: <span id="comment_count"><%= book.book_comments.count %></span></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_info-show.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:"100x100" %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>Follows</th>
    <th>
      <%= link_to user_follows_path(user.id) do %>
        <p id="flw_count_show"><%= user.follows.count%></p>
      <% end %>
    </th>
  </tr>
  <tr>
    <th>Followers</th>
    <th>
      <%= link_to  user_followers_path(user.id) do %>
        <p id=flwr_count_show><%= user.followers.count %></p>
      <% end %>
    </th>
  </tr>
</table>

<div class='row'>
  <% if user.id == current_user.id %>
    <td><%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %></td>
      <i class="fas fa-user-cog"></i>
    <% end %>
    
  <% else %>
    <div id="follow_btn_<%= user.id %>">
      <%= render "relationships/btn", user: user %>
    </div>
  <% end %>
</div>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		<%= render "layouts/errors", obj: @book %>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', @book %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <div>
    <%= render "layouts/errors", obj: @book %>
  </div>
  
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info-index', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'index', books: @books %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div>
    <%= render "layouts/errors", obj: @book %>
  </div>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info-show', user: @book.user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @new_book %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
          <td>
            <%= link_to @book.user do %>
              <%= image_tag @book.user.get_profile_image, size:"100x100" %><br>
              <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, @book %></td>
          <td><%= @book.body %></td>
          <% if @book.user_id == current_user.id %>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success" %></td>
            <td><%= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger"%></td>
          <% end %>
          
          <td id="favorite_btn_<%= @book.id %>">
            <%= render "favorites/favorite-btn", book: @book %>
          </td>
          <td>コメント数: <span id="comment_count"><%= @book.book_comments.count %></span></td>
        </tr>
      </table>
      
      <div id="book_comments">
        <%= render "book_comments/comments", book: @book %>
      </div>
      <div id="comment-form">
        <%= render "book_comments/form", book: @book, book_comment: @book_comment %>
      </div>
    </div>
  </div>
</div>

app/views/favorites/_favorite-btn.html.erb
<% if book.favorited_by?(current_user) %>
  <p>
    <%= link_to book_favorites_path(book), method: :delete, remote: true, class: "text-decoration-none text-danger" do %>
      <i class="fas fa-heart"></i><%= book.favorites.count %>
    <% end %>
  </p>
<% else %>
  <p>
    <%= link_to book_favorites_path(book), method: :post, remote: true, class: "text-decoration-none text-primary" do %>
      <i class="fas fa-heart"></i><%= book.favorites.count %>
    <% end %>
  </p>
<% end %>

app/views/favorites/create.js.erb
$("#favorite_btn_<%= @book.id %>").html("<%= j(render "favorites/favorite-btn", book: @book) %>");

app/views/favorites/destroy.js.erb
$("#favorite_btn_<%= @book.id %>").html("<%= j(render "favorites/favorite-btn", book: @book) %>");

app/views/homes/about.html.erb
<div class='container'>
  <div class='row'>
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to 'Log in',new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
        </div>
        <div class="row">
          <%= link_to 'Sign up',new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/relationships/_btn.html.erb
<% if user.id == current_user.id %>
  <td>
    <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  </td>
  
<% else %>
  <div id="follow_btn_<%= user.id %>">
    <% if current_user.following?(user) %>
      <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, remote: true, class: "btn btn-info btn-sm" %>
    <% else %>
      <%= link_to "フォローする", user_relationships_path(user.id), method: :post, remote: true, class: "btn btn-success btn-sm" %>
    <% end %>
  </div>
<% end %>

app/views/relationships/_ff-count.html.erb
<%= user.follows.count %>

app/views/relationships/create.js.erb
$("#follow_btn_<%= @user.id %>").html("<%= j(render "btn", user: @user) %>");

$("#flw_count").html("<%= current_user.follows.count%>");
$("#flwr_count").html("<%= current_user.followers.count%>");

$("#flw_count_show").html("<%= @user.follows.count%>");
$("#flwr_count_show").html("<%= @user.followers.count%>");

app/views/relationships/destroy.js.erb
$("#follow_btn_<%= @user.id %>").html("<%= j(render "btn", user: @user) %>");

$("#flw_count").html("<%= current_user.follows.count%>");
$("#flwr_count").html("<%= current_user.followers.count%>");

$("#flw_count_show").html("<%= @user.follows.count%>");
$("#flwr_count_show").html("<%= @user.followers.count%>");

app/views/relationships/followers.html.erb
<h2>Follower Users</h2>
<% if @users.exists? %>
  <%= render "users/index", users: @users %>
<% else %>
  <p>No followers yet!</p>
<% end %>

app/views/relationships/follows.html.erb
<h2>Follow Users</h2>
<% if @users.exists? %>
  <div id="ff_count_right">
    <%= render 'users/index', users: @users %>
  </div>
<% else %>
  <p>Not following anyone yet!</p>
<% end %>

app/views/searches/_search.html.erb
<% if user_signed_in? %>

  <div class="form-group d-flex justify-content-center">
    <%= form_with url: search_path, local: true, method: :get do |f| %>
      <%= f.text_field :searchword %>
      <%= f.select :range, options_for_select([["User"], ["Book"]]) %>
      <%= f.select :search, options_for_select([["完全一致","perfect"], ["前方一致", "forward"], ["後方一致", "backward"], ["部分一致", "partial"]])%>
      <%= f.submit "検索", class: "btn btn-outline-secondary btn-sm" %>
    <% end %>
  </div>
  
<% end %>

app/views/searches/search.html.erb
<% if @range == "User" %>
  <h3>User's search results for "<%= @searchword %>"</h3>
  
  <%= render "users/index", users: @users %>

<% elsif @range == "Book" %>
  <h3>Book's search results for "<%= @searchword %>"</h3>
  
  <%= render "books/index", books: @books %>
  
<% end %>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>フォロー数: <span id="flw_count_show"><%= user.follows.count%></span></td>
        <td>フォロワー数: <span id="flwr_count_show"><%= user.followers.count %></span></td>
        <td id="follow_btn_<%= user.id %>">
          <% if user.id != current_user.id %>
            <%= render "relationships/btn", user: user %>
          <% end %>
        </td>
        <td><%= link_to 'Show', user_path(user.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info-index.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:"100x100" %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>Follows</th>
    <th>
      <%= link_to user_follows_path(user.id) do %>
        <p id="flw_count"><%= user.follows.count%></p>
      <% end %>
    </th>
  </tr>
  <tr>
    <th>Followers</th>
    <th>
      <%= link_to  user_followers_path(user.id) do %>
        <p id=flwr_count><%= user.followers.count %></p>
      <% end %>
    </th>
  </tr>
</table>

<div class='row'>
  <% if user.id == current_user.id %>
    <td><%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %></td>
      <i class="fas fa-user-cog"></i>
    <% end %>
    
  <% else %>
    <div id="follow_btn_<%= user.id %>">
      <%= render "relationships/btn", user: user %>
    </div>
  <% end %>
</div>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:"100x100" %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
   <th>Follows</th>
   <th id="follow_count"><%= render "relationships/follow-count", user: user%></th>
  </tr>
  <tr>
    <th>Followers</th>
    <th id="follower_count"><%= render "relationships/follower-count", user: user%></th>
  </tr>
</table>

<div class='row'>
  <% if user.id == current_user.id %>
    <td><%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %></td>
      <i class="fas fa-user-cog"></i>
    <% end %>
    
  <% else %>
    <div id="follow_btn_<%= user.id %>">
      <%= render "relationships/btn", user: user %>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div>
    <%= render "layouts/errors", obj: @book %>
  </div>
  <div class='row'>
    
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render "info-index", user: current_user%>
      
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    
    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <%= render 'index', users: @users %>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div>
    <%= render "layouts/errors", obj: @book %>
  </div>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'books/info-show', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <div id="favorite_btn_<%= @book.id %>">
        <%= render 'books/index', books: @books %>
      </div>
    </div>
  </div>
</div>